import { useState } from 'react';

/**
 * Reusable AI analysis panel.
 */
export default function AIPanel({ fetchFn, label = 'AI ANALYSIS', resultKey = 'analysis' }) {
  const [state,  setState]  = useState('idle'); // idle | loading | done | error
  const [result, setResult] = useState('');
  const [error,  setError]  = useState('');

  const run = async () => {
    setState('loading');
    setResult('');
    setError('');
    try {
      const data = await fetchFn();
      setResult(data[resultKey] || 'No analysis returned.');
      setState('done');
    } catch (err) {
      setError(err.message || 'AI analysis failed.');
      setState('error');
    }
  };

  return (
    <div className="t-card" style={{ borderColor: 'rgba(255,140,0,0.2)', overflow: 'hidden' }}>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '10px 16px', borderBottom: '1px solid #1e1e1e',
        background: 'rgba(255,140,0,0.04)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ fontSize: '8px', color: '#FF8C00' }}>◈</span>
          <span className="t-label">CLAUDE AI · {label}</span>
        </div>
        {state === 'idle' || state === 'error' ? (
          <button onClick={run} className="t-btn" style={{ padding: '4px 12px', fontSize: '9px' }}>
            ↳ REQUEST
          </button>
        ) : state === 'loading' ? (
          <span style={{ fontFamily: 'IBM Plex Mono', fontSize: '9px', color: '#444', letterSpacing: '0.1em' }}>
            PROCESSING<span style={{ animation: 'blink 1s step-end infinite' }}>_</span>
          </span>
        ) : (
          <button onClick={() => setState('idle')} className="t-btn-ghost" style={{ padding: '4px 10px', fontSize: '9px' }}>
            ↺ RESET
          </button>
        )}
      </div>

      {/* Content */}
      <div style={{ padding: '14px 16px', minHeight: '48px' }}>
        {state === 'idle' && (
          <p style={{ fontFamily: 'IBM Plex Mono', fontSize: '10px', color: '#3a3a3a', lineHeight: 1.7 }}>
             Press REQUEST to generate an AI analysis of this data using Claude.
          </p>
        )}
        {state === 'loading' && (
          <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
            {[0,1,2,3,4].map(i => (
              <div key={i} style={{
                width: '3px', height: '12px', background: '#FF8C00',
                animation: `pulse-amber 1s ease-in-out ${i * 0.15}s infinite`,
                opacity: 0.3,
              }} />
            ))}
          </div>
        )}
        {state === 'done' && (
          <p style={{ fontFamily: 'IBM Plex Mono', fontSize: '11px', color: '#C8B89A', lineHeight: 1.8 }} className="animate-fade-in">
            {result}
          </p>
        )}
        {state === 'error' && (
          <p style={{ fontFamily: 'IBM Plex Mono', fontSize: '10px', color: '#FF3333', lineHeight: 1.7 }}>
            ERROR: {error}
          </p>
        )}
      </div>

      {state === 'done' && (
        <div style={{ padding: '6px 16px', borderTop: '1px solid #1e1e1e', background: '#0e0e0e' }}>
          <span style={{ fontFamily: 'IBM Plex Mono', fontSize: '8px', color: '#333', letterSpacing: '0.1em' }}>
            GENERATED BY CLAUDE · ANTHROPIC · NOT OFFICIAL NASA CONTENT
          </span>
        </div>
      )}
    </div>
  );
}